### PR TITLE
Update MAINTAINERS.MD

### PR DESCRIPTION
**Pull request by hdamker**
#### What type of PR is this?

Add one of the following kinds:
* subproject management

#### What this PR does / why we need it:

Create initial maintainer list

#### Which issue(s) this PR fixes:

Fixes partially https://github.com/camaraproject/APIBacklog/issues/37

### CODE REVIEW

**Review by Kevsy — APPROVED** [review]

**Review by Kevsy — APPROVED** [review]

**Comment by Kevsy** [comment]
@hdamker any idea why the merge is blocked? The messages above are contradictory:

"Kevsy approved these changes on behalf of https://github.com/orgs/camaraproject/teams/simple-edge-discovery_codeowners 1 hour ago]"

"Merging is blocked: Merging can be performed automatically with 1 approving review."

**Review by nicolacdnll — APPROVED** [review]

**Comment by hdamker** [comment]
@Kevsy The CODEOWNERS file defines that the group @camaraproject/admins owns the MAINTAINERS.md file. As this happened only after this PR, the group was not added automatically. Have added the colleagues now (I can't approve my own pull request).

**Comment by hdamker** [comment]
But you can start to work with the repository - the CODEOWNERS file is valid.

**Comment by hdamker** [comment]
Merged with admin rights.

**Pull request merged**
